# Generated by Django 5.1.8 on 2025-05-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
